# Generated by Django 2.2.7 on 2019-11-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=255, verbose_name='バンド名')),
                ('responsible_person_name', models.CharField(max_length=255, verbose_name='責任者名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_name', models.CharField(max_length=255, verbose_name='PA担当者名')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.Band')),
            ],
        ),
    ]
