# Generated by Django 2.2.7 on 2019-11-17 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(10)], verbose_name='バンド名'),
        ),
        migrations.AlterField(
            model_name='band',
            name='responsible_person_name',
            field=models.CharField(max_length=255, verbose_name='バンドマスター'),
        ),
    ]
