# Generated by Django 2.2.7 on 2019-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0002_auto_20191117_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_name',
            field=models.CharField(max_length=255, unique=True, verbose_name="Band's Name"),
        ),
        migrations.AlterField(
            model_name='band',
            name='responsible_person_name',
            field=models.CharField(max_length=255, verbose_name="Band Master's Name"),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='text',
            field=models.TextField(blank=True, verbose_name='備考欄'),
        ),
    ]
