# Generated by Django 2.2.7 on 2019-11-18 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0003_auto_20191117_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.TimeField(default=datetime.datetime(2019, 11, 18, 22, 44, 55, 391851, tzinfo=utc)),
        ),
    ]
